package com.gzz100.nameplate.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.gzz100.nameplate.bean.Device;
import com.gzz100.nameplate.bean.Account;

import com.gzz100.nameplate.dao.DeviceDao;
import com.gzz100.nameplate.dao.AccountDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig deviceDaoConfig;
    private final DaoConfig accountDaoConfig;

    private final DeviceDao deviceDao;
    private final AccountDao accountDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        deviceDaoConfig = daoConfigMap.get(DeviceDao.class).clone();
        deviceDaoConfig.initIdentityScope(type);

        accountDaoConfig = daoConfigMap.get(AccountDao.class).clone();
        accountDaoConfig.initIdentityScope(type);

        deviceDao = new DeviceDao(deviceDaoConfig, this);
        accountDao = new AccountDao(accountDaoConfig, this);

        registerDao(Device.class, deviceDao);
        registerDao(Account.class, accountDao);
    }
    
    public void clear() {
        deviceDaoConfig.clearIdentityScope();
        accountDaoConfig.clearIdentityScope();
    }

    public DeviceDao getDeviceDao() {
        return deviceDao;
    }

    public AccountDao getAccountDao() {
        return accountDao;
    }

}
